<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sGullk Application 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo in lectus vel feugiat. Sed risus sem, rutrum at consequat a, vehicula ut leo. Morbi interdum volutpat eros, a faucibus justo convallis non. In nec euismod sapien, in auctor augue. Ut tempor augue id pretium auctor."), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <!--<p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>-->
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Donec diam erat') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate("Vivamus quis erat lacus. Suspendisse nec aliquam leo. Donec ut semper sapien. Proin fringilla vehicula molestie. Vestibulum vel dolor eget ante feugiat pretium. Aliquam et tristique orci. Fusce sed euismod felis, commodo tempus nunc.")) ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('aliquam leo') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('suscipit id scelerisque') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate("In at venenatis velit, quis dignissim sem. Quisque semper volutpat diam ac semper. Donec egestas justo ac ligula ullamcorper, vitae eleifend nisi blandit.")) ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('eget dapibus non') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Maecenas id nibh') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate("Nullam vitae felis quis diam convallis tincidunt. Ut convallis, diam a lacinia scelerisque, sapien urna blandit risus, quis vestibulum sem ligula non odio")) ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('dignissim sem') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
